name: Update Recent Activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 5
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: "chore: update recent activity"
